#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $AUTH_USER WITH PASSWORD '$AUTH_PASSWORD';
    CREATE DATABASE $AUTH_DB OWNER $AUTH_USER;
    \connect auth
    GRANT ALL PRIVILEGES ON SCHEMA public TO $AUTH_USER;
    ALTER SCHEMA public OWNER TO $AUTH_USER;
EOSQL