services:

  traefik:
    image: traefik:v2.11
    container_name: q-traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.file.filename=/etc/traefik.dynamic.yml
      - --entrypoints.web.address=:80
    ports:
        - "80:80"
        - "8080:8080"
    volumes:
      - ./traefik.dynamic.yml:/etc/traefik.dynamic.yml
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres:17
    container_name: q-postgres
    restart: always
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      AUTH_DB: ${AUTH_DB}
      AUTH_USER: ${AUTH_USER}
      AUTH_PASSWORD: ${AUTH_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    container_name: q-redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redisdata:/data

  minio:
    image: minio/minio:latest
    container_name: q-minio
    ports:
      - "9002:9000"
      - "9003:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio:/data
    command: server /data --console-address ":9001"

volumes:
  pgdata:
  redisdata:
  minio: